import { create } from "zustand";
import { getAllTokens } from "../../design-system/src/utils/token-loader";

/**
 * Public toast shape. `id` is generated by `push` so callers can dismiss
 * a specific toast or let the auto-expiry timer handle it.
 */
export type Toast = {
  id: string;
  message: string;
  variant: ToastVariant;
  createdAt: number;
};

export type ToastVariant = "info" | "success" | "error";

type ToastInput = {
  message: string;
  variant?: ToastVariant;
  /** Override the default auto-dismiss duration in milliseconds. */
  durationMs?: number;
};

type ToastStore = {
  toasts: Toast[];
  push: (input: ToastInput) => string;
  dismiss: (id: string) => void;
  clear: () => void;
};

function defaultDuration(): number {
  const toast = getAllTokens().toast ?? {};
  if (typeof window !== "undefined" && window.matchMedia?.("(prefers-reduced-motion: reduce)").matches) {
    return toast.reducedMotionDurationMs ?? 1500;
  }
  return toast.defaultDurationMs ?? 4000;
}

function maxVisible(): number {
  return getAllTokens().toast?.maxVisible ?? 5;
}

let _idCounter = 0;
function nextId(): string {
  _idCounter += 1;
  return `toast-${Date.now().toString(36)}-${_idCounter}`;
}

/**
 * Zustand-backed toast queue. Toasts auto-dismiss after the supplied
 * duration (or the default) and are evicted FIFO when the visible cap is
 * reached. The store is intentionally headless — the visible surface is
 * `ToastViewport`, which subscribes via the `toasts` selector.
 *
 * Default durations and the visible cap are read from the design-system
 * tokens:
 * - `tokens.toast.defaultDurationMs` (4000)
 * - `tokens.toast.reducedMotionDurationMs` (1500)
 * - `tokens.toast.maxVisible` (5)
 *
 * Pass a custom `durationMs` to override the default for a single toast
 * (e.g. errors that should linger). Pass `0` (or a negative number) to
 * disable auto-dismiss for that toast entirely.
 */
export const useToastStore = create<ToastStore>((set, get) => {
  // Use a plain object (not a Map) to stay compatible with the project's
  // TypeScript `lib` target that pre-dates `Map`/`Set` in the global scope.
  const timers: Record<string, ReturnType<typeof setTimeout>> = {};

  function clearTimer(id: string) {
    const t = timers[id];
    if (t !== undefined) {
      clearTimeout(t);
      delete timers[id];
    }
  }

  function push(input: ToastInput): string {
    const id = nextId();
    const variant = input.variant ?? "info";
    const toast: Toast = {
      id,
      message: input.message,
      variant,
      createdAt: Date.now(),
    };

    set((state) => {
      const merged = [...state.toasts, toast];
      const cap = maxVisible();
      if (merged.length > cap) {
        const evicted = merged.slice(0, merged.length - cap);
        for (const t of evicted) clearTimer(t.id);
        return { toasts: merged.slice(-cap) };
      }
      return { toasts: merged };
    });

    const duration = input.durationMs ?? defaultDuration();
    if (duration > 0) {
      const handle = setTimeout(() => {
        delete timers[id];
        get().dismiss(id);
      }, duration);
      timers[id] = handle;
    }

    return id;
  }

  function dismiss(id: string) {
    clearTimer(id);
    set((state) => ({ toasts: state.toasts.filter((t) => t.id !== id) }));
  }

  function clear() {
    for (const id of Object.keys(timers)) clearTimer(id);
    set({ toasts: [] });
  }

  return {
    toasts: [],
    push,
    dismiss,
    clear,
  };
});

/**
 * Test-only escape hatch. Clears every pending auto-dismiss timer and
 * resets the toast queue. Not part of the production API.
 */
export function __resetToastStoreForTests() {
  useToastStore.getState().clear();
}
