import { create } from "zustand";

/**
 * Timing and capacity defaults — mirrored from
 * `design-system/tokens/toast.json` and documented in
 * `design-system/documentation/toast.md`. Kept as plain constants so the
 * store runs in the browser without the Node-only design-system token loader.
 */
export const TOAST_DEFAULT_DURATION_MS = 4000;
export const TOAST_REDUCED_MOTION_DURATION_MS = 1500;
export const TOAST_MAX_VISIBLE = 5;

export type ToastVariant = "info" | "success" | "error";

/**
 * Public toast shape. `id` is generated by `push` so callers can dismiss
 * a specific toast or let the auto-expiry timer handle it.
 */
export type Toast = {
  id: string;
  message: string;
  variant: ToastVariant;
  createdAt: number;
};

export type ToastInput = {
  message: string;
  variant?: ToastVariant;
  /** Override the default auto-dismiss duration in milliseconds. */
  durationMs?: number;
};

type ToastStore = {
  toasts: Toast[];
  push: (input: ToastInput) => string;
  dismiss: (id: string) => void;
  clear: () => void;
};

function prefersReducedMotion(): boolean {
  return (
    typeof window !== "undefined" &&
    Boolean(window.matchMedia?.("(prefers-reduced-motion: reduce)").matches)
  );
}

function defaultDuration(): number {
  return prefersReducedMotion()
    ? TOAST_REDUCED_MOTION_DURATION_MS
    : TOAST_DEFAULT_DURATION_MS;
}

let _idCounter = 0;
function nextId(): string {
  _idCounter += 1;
  return `toast-${Date.now().toString(36)}-${_idCounter}`;
}

/**
 * Zustand-backed toast queue. Toasts auto-dismiss after the supplied
 * duration (or the default) and are evicted FIFO when the visible cap is
 * reached. The store is intentionally headless — the visible surface is
 * `ToastViewport`, which subscribes via the `toasts` selector.
 *
 * Defaults:
 * - `TOAST_DEFAULT_DURATION_MS` (4000)
 * - `TOAST_REDUCED_MOTION_DURATION_MS` (1500) when prefers-reduced-motion
 * - `TOAST_MAX_VISIBLE` (5)
 *
 * Pass a custom `durationMs` to override the default for a single toast
 * (e.g. errors that should linger). Pass `0` (or a negative number) to
 * disable auto-dismiss for that toast entirely.
 */
export const useToastStore = create<ToastStore>((set, get) => {
  // Plain object (not a Map) keeps timer bookkeeping simple and testable.
  const timers: Record<string, ReturnType<typeof setTimeout>> = {};

  function clearTimer(id: string) {
    const t = timers[id];
    if (t !== undefined) {
      clearTimeout(t);
      delete timers[id];
    }
  }

  function push(input: ToastInput): string {
    const id = nextId();
    const variant = input.variant ?? "info";
    const toast: Toast = {
      id,
      message: input.message,
      variant,
      createdAt: Date.now(),
    };

    set((state) => {
      const merged = [...state.toasts, toast];
      const cap = TOAST_MAX_VISIBLE;
      if (merged.length > cap) {
        const evicted = merged.slice(0, merged.length - cap);
        for (const t of evicted) clearTimer(t.id);
        return { toasts: merged.slice(-cap) };
      }
      return { toasts: merged };
    });

    const duration = input.durationMs ?? defaultDuration();
    if (duration > 0) {
      const handle = setTimeout(() => {
        delete timers[id];
        get().dismiss(id);
      }, duration);
      timers[id] = handle;
    }

    return id;
  }

  function dismiss(id: string) {
    clearTimer(id);
    set((state) => ({ toasts: state.toasts.filter((t) => t.id !== id) }));
  }

  function clear() {
    for (const id of Object.keys(timers)) clearTimer(id);
    set({ toasts: [] });
  }

  return {
    toasts: [],
    push,
    dismiss,
    clear,
  };
});

/**
 * Test-only escape hatch. Clears every pending auto-dismiss timer and
 * resets the toast queue. Not part of the production API.
 */
export function __resetToastStoreForTests() {
  useToastStore.getState().clear();
}
